spring:
  datasource:
    url: jdbc:hsqldb:file:./data/demo
    driver-class-name: org.hsqldb.jdbcDriver

  security:
    secretkey: zdtlD3JK56m6wTTgsNFhqzjqP

    failedlogin:
      count: 5

  liquibase:
    change-log: classpath:liquibase/changelog-master.xml

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.HSQLDialect
    defer-datasource-initialization: false
    show-sql: true
